// Code generated by go-swagger; DO NOT EDIT.

package update_product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hsedjame/products-api/client/models"
)

// UpdateProductReader is a Reader for the UpdateProduct structure.
type UpdateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewUpdateProductNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateProductOK creates a UpdateProductOK with default headers values
func NewUpdateProductOK() *UpdateProductOK {
	return &UpdateProductOK{}
}

/*UpdateProductOK handles this case with default header values.

product updated successfully
*/
type UpdateProductOK struct {
	Payload []*models.Product
}

func (o *UpdateProductOK) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateProductOK  %+v", 200, o.Payload)
}

func (o *UpdateProductOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *UpdateProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductBadRequest creates a UpdateProductBadRequest with default headers values
func NewUpdateProductBadRequest() *UpdateProductBadRequest {
	return &UpdateProductBadRequest{}
}

/*UpdateProductBadRequest handles this case with default header values.

bad request
*/
type UpdateProductBadRequest struct {
	Payload *models.GenericError
}

func (o *UpdateProductBadRequest) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateProductBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateProductBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductNotAcceptable creates a UpdateProductNotAcceptable with default headers values
func NewUpdateProductNotAcceptable() *UpdateProductNotAcceptable {
	return &UpdateProductNotAcceptable{}
}

/*UpdateProductNotAcceptable handles this case with default header values.

request not acceptable error
*/
type UpdateProductNotAcceptable struct {
	Payload *models.ValidationError
}

func (o *UpdateProductNotAcceptable) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateProductNotAcceptable  %+v", 406, o.Payload)
}

func (o *UpdateProductNotAcceptable) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateProductNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductInternalServerError creates a UpdateProductInternalServerError with default headers values
func NewUpdateProductInternalServerError() *UpdateProductInternalServerError {
	return &UpdateProductInternalServerError{}
}

/*UpdateProductInternalServerError handles this case with default header values.

internal server error
*/
type UpdateProductInternalServerError struct {
	Payload *models.GenericError
}

func (o *UpdateProductInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateProductInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateProductInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
