// Code generated by go-swagger; DO NOT EDIT.

package delete_product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hsedjame/products-api/client/models"
)

// DeleteProductReader is a Reader for the DeleteProduct structure.
type DeleteProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteProductOK creates a DeleteProductOK with default headers values
func NewDeleteProductOK() *DeleteProductOK {
	return &DeleteProductOK{}
}

/*DeleteProductOK handles this case with default header values.

product updated successfully
*/
type DeleteProductOK struct {
	Payload bool
}

func (o *DeleteProductOK) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductOK  %+v", 200, o.Payload)
}

func (o *DeleteProductOK) GetPayload() bool {
	return o.Payload
}

func (o *DeleteProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductInternalServerError creates a DeleteProductInternalServerError with default headers values
func NewDeleteProductInternalServerError() *DeleteProductInternalServerError {
	return &DeleteProductInternalServerError{}
}

/*DeleteProductInternalServerError handles this case with default header values.

internal server error
*/
type DeleteProductInternalServerError struct {
	Payload *models.GenericError
}

func (o *DeleteProductInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteProductInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
