// Code generated by go-swagger; DO NOT EDIT.

package create_product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hsedjame/products-api/client/models"
)

// CreateProductReader is a Reader for the CreateProduct structure.
type CreateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewCreateProductNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProductOK creates a CreateProductOK with default headers values
func NewCreateProductOK() *CreateProductOK {
	return &CreateProductOK{}
}

/*CreateProductOK handles this case with default header values.

product found
*/
type CreateProductOK struct {
	Payload []*models.Product
}

func (o *CreateProductOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProductOK  %+v", 200, o.Payload)
}

func (o *CreateProductOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *CreateProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductBadRequest creates a CreateProductBadRequest with default headers values
func NewCreateProductBadRequest() *CreateProductBadRequest {
	return &CreateProductBadRequest{}
}

/*CreateProductBadRequest handles this case with default header values.

bad request
*/
type CreateProductBadRequest struct {
	Payload *models.GenericError
}

func (o *CreateProductBadRequest) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProductBadRequest  %+v", 400, o.Payload)
}

func (o *CreateProductBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductNotAcceptable creates a CreateProductNotAcceptable with default headers values
func NewCreateProductNotAcceptable() *CreateProductNotAcceptable {
	return &CreateProductNotAcceptable{}
}

/*CreateProductNotAcceptable handles this case with default header values.

not acceptable error
*/
type CreateProductNotAcceptable struct {
	Payload *models.ValidationError
}

func (o *CreateProductNotAcceptable) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProductNotAcceptable  %+v", 406, o.Payload)
}

func (o *CreateProductNotAcceptable) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateProductNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductInternalServerError creates a CreateProductInternalServerError with default headers values
func NewCreateProductInternalServerError() *CreateProductInternalServerError {
	return &CreateProductInternalServerError{}
}

/*CreateProductInternalServerError handles this case with default header values.

internal server error
*/
type CreateProductInternalServerError struct {
	Payload *models.GenericError
}

func (o *CreateProductInternalServerError) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProductInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateProductInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
