// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListOfProductsParams creates a new ListOfProductsParams object
// with the default values initialized.
func NewListOfProductsParams() *ListOfProductsParams {

	return &ListOfProductsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListOfProductsParamsWithTimeout creates a new ListOfProductsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListOfProductsParamsWithTimeout(timeout time.Duration) *ListOfProductsParams {

	return &ListOfProductsParams{

		timeout: timeout,
	}
}

// NewListOfProductsParamsWithContext creates a new ListOfProductsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListOfProductsParamsWithContext(ctx context.Context) *ListOfProductsParams {

	return &ListOfProductsParams{

		Context: ctx,
	}
}

// NewListOfProductsParamsWithHTTPClient creates a new ListOfProductsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListOfProductsParamsWithHTTPClient(client *http.Client) *ListOfProductsParams {

	return &ListOfProductsParams{
		HTTPClient: client,
	}
}

/*ListOfProductsParams contains all the parameters to send to the API endpoint
for the list of products operation typically these are written to a http.Request
*/
type ListOfProductsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list of products params
func (o *ListOfProductsParams) WithTimeout(timeout time.Duration) *ListOfProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list of products params
func (o *ListOfProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list of products params
func (o *ListOfProductsParams) WithContext(ctx context.Context) *ListOfProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list of products params
func (o *ListOfProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list of products params
func (o *ListOfProductsParams) WithHTTPClient(client *http.Client) *ListOfProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list of products params
func (o *ListOfProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListOfProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
