// Code generated by go-swagger; DO NOT EDIT.

package product_by_name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProductByNameParams creates a new GetProductByNameParams object
// with the default values initialized.
func NewGetProductByNameParams() *GetProductByNameParams {
	var ()
	return &GetProductByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductByNameParamsWithTimeout creates a new GetProductByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductByNameParamsWithTimeout(timeout time.Duration) *GetProductByNameParams {
	var ()
	return &GetProductByNameParams{

		timeout: timeout,
	}
}

// NewGetProductByNameParamsWithContext creates a new GetProductByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductByNameParamsWithContext(ctx context.Context) *GetProductByNameParams {
	var ()
	return &GetProductByNameParams{

		Context: ctx,
	}
}

// NewGetProductByNameParamsWithHTTPClient creates a new GetProductByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductByNameParamsWithHTTPClient(client *http.Client) *GetProductByNameParams {
	var ()
	return &GetProductByNameParams{
		HTTPClient: client,
	}
}

/*GetProductByNameParams contains all the parameters to send to the API endpoint
for the get product by name operation typically these are written to a http.Request
*/
type GetProductByNameParams struct {

	/*Name
	  name of product

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get product by name params
func (o *GetProductByNameParams) WithTimeout(timeout time.Duration) *GetProductByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get product by name params
func (o *GetProductByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get product by name params
func (o *GetProductByNameParams) WithContext(ctx context.Context) *GetProductByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get product by name params
func (o *GetProductByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get product by name params
func (o *GetProductByNameParams) WithHTTPClient(client *http.Client) *GetProductByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get product by name params
func (o *GetProductByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get product by name params
func (o *GetProductByNameParams) WithName(name string) *GetProductByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get product by name params
func (o *GetProductByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
