// Code generated by go-swagger; DO NOT EDIT.

package product_by_name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hsedjame/products-api/client/models"
)

// GetProductByNameReader is a Reader for the GetProductByName structure.
type GetProductByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProductByNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProductByNameOK creates a GetProductByNameOK with default headers values
func NewGetProductByNameOK() *GetProductByNameOK {
	return &GetProductByNameOK{}
}

/*GetProductByNameOK handles this case with default header values.

product found
*/
type GetProductByNameOK struct {
	Payload *models.Product
}

func (o *GetProductByNameOK) Error() string {
	return fmt.Sprintf("[GET /products/{name}][%d] getProductByNameOK  %+v", 200, o.Payload)
}

func (o *GetProductByNameOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *GetProductByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductByNameBadRequest creates a GetProductByNameBadRequest with default headers values
func NewGetProductByNameBadRequest() *GetProductByNameBadRequest {
	return &GetProductByNameBadRequest{}
}

/*GetProductByNameBadRequest handles this case with default header values.

bad request
*/
type GetProductByNameBadRequest struct {
	Payload *models.GenericError
}

func (o *GetProductByNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /products/{name}][%d] getProductByNameBadRequest  %+v", 400, o.Payload)
}

func (o *GetProductByNameBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetProductByNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
